{
 "title": "Azure SQL MI",
 "tags": [ "SQLMI" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "instance", "label": "Database", "query": { "query": "mssqlmi_cpu_count" } }
  ]
 },
 "panels": [
  { "title": "Managed Instance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Virtual Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssqlmi_cpu_count{instance=~\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssqlmi_server_memory_bytes{instance=~\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Tier",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssqlmi_total_storage_bytes{instance=~\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Level Objective",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssqlmi_total_storage_bytes{instance=~\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssqlmi_total_storage_bytes{instance=~\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssqlmi_available_storage_bytes{instance=~\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Databases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssqlmi_db_online{instance=~\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Usage %",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(mssqlmi_total_storage_bytes{instance=~\"${instance}\"} - ignoring(instance,hardware_type,sku) mssqlmi_available_storage_bytes{instance=~\"${instance}\"}) / ignoring(instance,hardware_type,sku) mssqlmi_total_storage_bytes{instance=~\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mssqlmi_database_size_bytes{instance=~\"${instance}\"}",
     "legendFormat": "{{file_type}} {{database}}"
    }
   ]
  },
  { "title": "SQL Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Batch Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(mssqlmi_perf_counter{counter=\"Batch Requests/sec\",instance=~\"${instance}\"}[$__interval])",
     "legendFormat": "{{counter}}"
    },
    {
     "expr": "rate(mssqlmi_perf_counter{counter=\"SQL Compilations/sec\",instance=~\"${instance}\"}[$__interval])",
     "legendFormat": "{{counter}}"
    },
    {
     "expr": "rate(mssqlmi_perf_counter{counter=\"SQL Re-Compilations/sec\",instance=~\"${instance}\"}[$__interval])",
     "legendFormat": "{{counter}}"
    }
   ]
  },
  {
   "title": "Transactions/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(mssqlmi_perf_counter{counter=\"Transactions/sec\",instance=~\"${instance}\"}[$__interval])",
     "legendFormat": "{{db}}"
    }
   ]
  },
  { "title": "CPU and Queuing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Total %CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(mssqlmi_perf_gauge{gauge=\"CPU usage %\", object=~\".*Resource Pool Stats\", instance=~\"${instance}\"})",
     "legendFormat": "CPU usage %"
    }
   ]
  },
  {
   "title": "Workload Group - %CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mssqlmi_perf_gauge{gauge=\"CPU usage %\", object=~\".*Workload Group Stats\", instance=~\"${instance}\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  { "title": "Waits and Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Wait Times by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(mssqlmi_wait_time_seconds{instance=~\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{wait_type}}"
    }
   ]
  },
  {
   "title": "Wait Times by Category",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(wait_category) (rate(mssqlmi_wait_time_seconds{instance=~\"${instance}\"}[$__rate_interval]))",
     "legendFormat": "{{wait_category}}"
    }
   ]
  },
  {
   "title": "Signal Wait Times by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(mssqlmi_signal_wait_time_seconds{instance=~\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{wait_type}}"
    }
   ]
  },
  {
   "title": "Signal Wait Times by Category",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(wait_category) (rate(mssqlmi_signal_wait_time_seconds{instance=~\"${instance}\"}[$__rate_interval]))",
     "legendFormat": "{{wait_category}}"
    }
   ]
  },
  {
   "title": "Waiting Tasks by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(mssqlmi_waiting_tasks_count{instance=~\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{wait_type}}"
    }
   ]
  },
  {
   "title": "Waiting Tasks by Category",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(wait_category) (rate(mssqlmi_waiting_tasks_count{instance=~\"${instance}\"}[$__rate_interval]))",
     "legendFormat": "{{wait_category}}"
    }
   ]
  },
  { "title": "Log Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Log Bytes Flushed/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(mssqlmi_perf_counter{counter=\"Log Bytes Flushed/sec\", instance=~\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Log Flushes/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(mssqlmi_perf_counter{counter=\"Log Flushes/sec\", instance=~\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{db}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Memory Manager",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "mssqlmi_perf_gauge{object=~\".*Memory Manager\", instance=~\"${instance}\"}",
     "legendFormat": "{{gauge}}"
    }
   ]
  },
  {
   "title": "Memory Clerks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "mssqlmi_clerk_size_kilobytes{instance=~\"${instance}\"}",
     "legendFormat": "{{clerk_type}}"
    }
   ]
  },
  {
   "title": "Page Life Expectancy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "mssqlmi_perf_gauge{gauge=\"Page life expectancy\", instance=~\"${instance}\"}",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "Buffer Manager",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(mssqlmi_perf_counter{object=~\".*Buffer Manager\", instance=~\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{counter}}"
    }
   ]
  },
  {
   "title": "Access Methods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(mssqlmi_perf_counter{object=~\".*Access Methods\", instance=~\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{counter}}"
    }
   ]
  },
  {
   "title": "General Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(mssqlmi_perf_counter{object=~\".*General Statistics\", instance=~\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{counter}}"
    }
   ]
  }
 ]
}