{{- if .Values.collectorFiles }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sql-exporter.fullname" . }}
  labels:
    app: {{ include "sql-exporter.fullname" . }}
    chart: {{ template "sql-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- include "sql-exporter.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.collectorFiles }}
  {{ $k }}: |-
    {{- toYaml $v | nindent 4}}
  {{- end}}
{{- end }}
