# Example: Kubernetes Secret for Database Connection String (DSN)
# This file shows how to create a secret containing a database DSN for dynamic config generation
#
# There are multiple ways to create this secret:

# ============================================================================
# Method 1: kubectl create secret (Recommended - simplest)
# ============================================================================
# Create a secret with a database DSN (Data Source Name):
#
# PostgreSQL:
#   kubectl create secret generic database-credentials \
#     --from-literal=dsn='username:password@hostname:5432/database?sslmode=disable' \
#     --namespace=your-namespace
#
# MySQL:
#   kubectl create secret generic database-credentials \
#     --from-literal=dsn='username:password@tcp(hostname:3306)/database' \
#     --namespace=your-namespace
#
# MSSQL:
#   kubectl create secret generic database-credentials \
#     --from-literal=dsn='sqlserver://username:password@hostname:1433?database=dbname' \
#     --namespace=your-namespace

# ============================================================================
# Method 2: kubectl apply -f (from YAML manifest)
# ============================================================================
# If you want to store the secret definition in version control:
#
# Step 1: Base64 encode your DSN:
#   Linux/Mac:
#     echo -n 'username:password@hostname:5432/database?sslmode=disable' | base64
#   Windows PowerShell:
#     [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes('username:password@hostname:5432/database?sslmode=disable'))
#
# Step 2: Copy the base64 value into the YAML below and apply:
#   kubectl apply -f secret-database.yaml

---
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: default  # Change to your namespace
  labels:
    app: sql-exporter
type: Opaque
data:
  # Base64-encoded DSN
  # This example encodes: "postgres:mypassword@postgres.default.svc.cluster.local:5432/mydb?sslmode=disable"
  # Replace this with your actual base64-encoded DSN
  dsn: cG9zdGdyZXM6bXlwYXNzd29yZEBwb3N0Z3Jlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvbXlkYj9zc2xtb2RlPWRpc2FibGU=

# ============================================================================
# Method 3: Service Binding Operator (Cloud-native)
# ============================================================================
# If you use Service Binding Operator or similar, the secret is automatically
# created by the database operator/broker. Just reference it in your values:
#
# dynamicConfig:
#   enabled: true
#   secretName: postgres-binding  # Created by operator
#   secretKey: uri                # or dsn, connection_string, etc.
#   type: postgres

# ============================================================================
# Method 4: External Secrets Operator (Recommended for production)
# ============================================================================
# If you have External Secrets Operator installed, reference DSN from
# external secret managers (AWS Secrets Manager, HashiCorp Vault, etc.):
#
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: database-credentials
#   namespace: default
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: your-secret-store
#     kind: SecretStore
#   target:
#     name: database-credentials  # Name of secret to create
#     creationPolicy: Owner
#   data:
#     - secretKey: dsn
#       remoteRef:
#         key: database/connection-string  # Path in your secret manager

# ============================================================================
# DSN Format Examples by Database Type
# ============================================================================
# PostgreSQL:
#   Standard: username:password@hostname:5432/database
#   With options: username:password@hostname:5432/database?sslmode=require&connect_timeout=10
#   Socket: username:password@/var/run/postgresql/database
#
# MySQL:
#   Standard: username:password@tcp(hostname:3306)/database
#   With options: username:password@tcp(hostname:3306)/database?parseTime=true&timeout=10s
#   Socket: username:password@unix(/var/run/mysqld/mysqld.sock)/database
#
# Microsoft SQL Server:
#   Standard: sqlserver://username:password@hostname:1433?database=dbname
#   With instance: sqlserver://username:password@hostname:1433?database=dbname&instance=SQLEXPRESS
#   Windows auth: sqlserver://hostname:1433?database=dbname&integrated security=sspi
#
# Oracle:
#   Standard: username/password@hostname:1521/service_name
#   With SID: username/password@hostname:1521:SID
#
# Clickhouse:
#   Standard: tcp://hostname:9000?database=dbname&username=user&password=pass
#   With options: tcp://hostname:9000?database=dbname&username=user&password=pass&read_timeout=10&write_timeout=10
#
# Snowflake:
#   Standard: username:password@account.region.snowflakecomputing.com:443/database?warehouse=wh
#   With role: username:password@account.region.snowflakecomputing.com:443/database?warehouse=wh&role=myrole

# ============================================================================
# Important Notes
# ============================================================================
# 1. The secret MUST be in the same namespace as the sql-exporter pod
# 2. The DSN format varies by database type - see examples above
# 3. The DSN should NOT include the driver prefix (postgres://, mysql://, etc.)
#    as it will be added by the init container based on dynamicConfig.type
# 4. Special characters in passwords should be URL-encoded:
#    @ -> %40, # -> %23, % -> %25, etc.
# 5. For production, use proper secrets management (Vault, External Secrets, etc.)
# 6. Never commit connection strings with credentials to version control
# 7. Rotate database passwords regularly
# 8. Consider using IAM authentication or similar for cloud databases
# 9. The secret key name defaults to 'dsn' but can be customized via:
#    dynamicConfig.secretKey

# ============================================================================
# Verify the secret
# ============================================================================
# After creating the secret, verify it:
#
#   kubectl get secret database-credentials
#   kubectl describe secret database-credentials
#
# Retrieve the DSN (for verification):
#
#   kubectl get secret database-credentials -o jsonpath='{.data.dsn}' | base64 -d

