repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: postgres-instance
    installed: true
    namespace: default
    chart: bitnami/postgresql
    values:
      - global:
          postgresql:
            auth:
              postgresPassword: 123123!!
