name: Go

on:
  push:
    branches:
     - master
  pull_request:
    branches:
     - master

jobs:
  build:
    if: ${{ !startsWith(github.event.head_commit.message, 'docs:') }}
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.20
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Style
      run: make style
    - name: Vet
      run: make vet
    - name: Test
      run: make test
    - name: Build
      run: make build
