name: Publish artifacts (linux distro)

on:
  workflow_dispatch:
  push:
    tags:
    - '*.*.*'

jobs:
  build:
    name: Build and upload artifacts
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make build

    - name: Create a deb package
      id: nfpm-deb
      uses: burningalchemist/action-gh-nfpm@v1
      with:
        packager: deb
        config: packaging/conf/nfpm.yaml
    - name: Create a rpm package
      id: nfpm-rpm
      uses: burningalchemist/action-gh-nfpm@v1
      with:
        packager: rpm
        config: packaging/conf/nfpm.yaml

    - name: Upload deb|rpm packages
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ steps.nfpm-deb.outputs.package }}
          ${{ steps.nfpm-rpm.outputs.package }}
