name: Build and Publish artifacts

on:
  workflow_dispatch:
  push:
    tags:
    - '*.*.*'

jobs:
  build:
    name: Build and upload artifacts
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Promu - Crossbuild
      run: make crossbuild

    - name: Promu - Prepare packages
      run: make crossbuild-tarballs

    - name: Create deb package
      uses: burningalchemist/action-gh-nfpm@v1
      with:
        packager: deb
        config: packaging/conf/nfpm.yaml
        target: .tarballs/
    - name: Create rpm package
      uses: burningalchemist/action-gh-nfpm@v1
      with:
        packager: rpm
        config: packaging/conf/nfpm.yaml
        target: .tarballs/

    - name: Calculate checksums
      run: make crossbuild-checksum

    - name: Upload artifacts
      uses: softprops/action-gh-release@v1
      with:
        files: |
          .tarballs/*
  docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: burningalchemist/sql_exporter
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          provenance: false
